# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/70c2ffd7-066a-4466-a02f-24ec6ffb2ca9";
      fsType = "btrfs";
      options = [ "subvol=Root" "compress=zstd:15" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/70c2ffd7-066a-4466-a02f-24ec6ffb2ca9";
      fsType = "btrfs";
      options = [ "subvol=Nix" "compress=zstd:15" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/70c2ffd7-066a-4466-a02f-24ec6ffb2ca9";
      fsType = "btrfs";
      options = [ "subvol=Home" "compress=zstd:15" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4DA0-EA45";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
